### ISSUE TITLE
User images overly video on smaller screens

### ISSUE THREAD

**Issue by Chickenbreadlp** [crybapp/web#101]
In cases where the player is larger than then available space on screen, then the profile pictures of those who are viewing are overlaying the video stream
![Example Image](https://user-images.githubusercontent.com/7395653/72672600-9639e400-3a5c-11ea-8b16-4cf0d76088eb.png)

**Comment by jeda** [comment]
Huh.

This is a new one, didn't notice before while testing. Must be something that got with the `@cryb/borealis` integration. 

We'll take a look at this, thanks for reporting!
