### ISSUE TITLE
If jsmpeg etc. hasn't loaded, viewer will try to use it and then crash

### ISSUE THREAD

**Issue by jeda** [crybapp/web#11]
If for example, we've not used Cryb before, and get invited to a room and we're joining, and `jsmpeg.min.js` hasn't loaded, it will try to use it anyway and then crash as JSMpeg is not defined.

In any case, and to prevent more issues, we should wait until all resources have been loaded in order to start stuff.

![](https://safe.install.sex/2hOOyE.png)

**Comment by lnneth** [comment]
Thats an odd issue, I’d say all you need to solve this is a little setTimeout()/sleep() before creating the player or a loop until window.JSMeg is defined

**Comment by jeda** [comment]
Or wait for everything to load.

**Comment by darnfish** [comment]
Just reproduced this locally, will look into fixing this ASAP.
![image](https://user-images.githubusercontent.com/8293444/67134141-6cc4ae80-f208-11e9-8c8b-c1be6b8c1133.png)

**Comment by jeda** [comment]
Not sure if this is happening still, as a fix was commited some time ago but not sure if it still happens. In any case, the fix is not good enough as it'd just not do anything.

**Comment by jeda** [comment]
Apparently it's not happening anymore. If it does, feel free to comment here so I reopen the issue. Closing for now!
