### ISSUE TITLE
Add information/animation if stream is currently not up

### ISSUE THREAD

**Issue by jeda** [crybapp/web#12]
As of right now, if stream is not happening, all you'll get is a white box. A way of detecting if JSMpeg is decoding stuff or not, and then add an animation such as Loading, or information to hang on or report an issue, could be done for this.

**Comment by lnneth** [comment]
This is possible with the JSMeg.Player option “placeholder” (I think that is what its called), however normally if the stream is functioning correctly you should not see a white box
