### ISSUE TITLE
Only the guest is able to control the mouse of the VM

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#13]
If I host a room and try to control the mouse it never works. However, if I give it to someone else it works fine.

**Comment by darnfish** [comment]
Are you able to control the VM when you take back control after handing the remote to someone else?

**Comment by jeda** [comment]
There was mentions in the Discord server that wouldn't work - a refresh would work, though. Another user had the exact issue, either way.

**Comment by jeda** [comment]
This was fixed with past changes, leading to the controller bug not happen again.
