### ISSUE TITLE
Make a invite button in the menu

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#14]
If someone joined the room, the invite at the bottom disappears. I think it would be nice to have a button that will copy the link in the menu in case you need the link again. 
![image](https://user-images.githubusercontent.com/26326692/67023062-2ff59c00-f0d0-11e9-8e78-8677fb6036e6.png)

**Comment by plusreed** [comment]
I believe this is under the "Room Menu" by clicking the Cryb logo in the top left.

**Comment by Simonx22** [comment]
You're right! Sorry, didn't see that.
