### ISSUE TITLE
Make Google Analytics tracking configurable

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#15]
There is a Google Analytics link which (likely) was used for cryb.app. It would be nice to make this configurable and maybe disabled by default.
https://github.com/crybapp/web/blob/50d6c21e43369dc51997968e3347429d89d4dbf8/layouts/logged-out.vue#L23
https://github.com/crybapp/web/blob/50d6c21e43369dc51997968e3347429d89d4dbf8/layouts/default.vue#L33

**Comment by darnfish** [comment]
Oh word, I'll add that in brand/config.js now!

**Comment by darnfish** [comment]
Added support in https://github.com/crybapp/web/commit/0243a80f3977923f4f338d45f98bcec154aa4ea1, closing out this issue - ty for the feature request!
