### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by jeda** [crybapp/web#2]
If you try to logout, nothing will happen - more like, it'll raise an error.

**Comment by Akrilla** [comment]
wrong button - this is an issue

**Comment by darnfish** [comment]
This is a known issue with Cookies under store/index.js, will look into this!

**Comment by darnfish** [comment]
Fixed this a couple days ago with https://github.com/crybapp/web/commit/6bc5da88562a1a35dc321dab7c7fc9b64c854996, forgot to close this issue!
