### ISSUE TITLE
Ability to close a room

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#22]
The host should have the ability to close the room and kick everyone out. Right now, the host can only leave it and the other people will still be inside the room.

**Comment by plusreed** [comment]
I thought the "Delete Room" option in the Room Options menu did this.

I can't test right now so I might need external confirmation /cc @williamsthing

**Comment by Simonx22** [comment]
You're right, sorry. I thought the cryb logo on the left will lead to the home page. I just tested it and it works fine. Closing this.

**Comment by darnfish** [comment]
Just a further comment, the Cryb logo on the room page will only show that menu if the user is the owner of the room, in case you / anyone else was confused!
