### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#26]
Dark mode support for other pages would be nice. We can use the prefers-color-scheme CSS feature. I'm interested to work on this so I'll see what I can do later

**Comment by darnfish** [comment]
Ah this would be really cool, we are planning to have a global light/dark theme support but hooking into that CSS API would be epic too. Not sure when we'll be able to do this but it's on the roadmap 👍

**Comment by darnfish** [comment]
Changed assignment at @Simonx22's request 😄
