### ISSUE TITLE
Room aren't synced

### ISSUE THREAD

**Issue by jeda** [crybapp/web#3]
Seems to be an issue with WebSockets. No new chat messages, people entering the room, or the state of the VM spinning up.

**Comment by darnfish** [comment]
If there's no console errors relating to WebSockets, this is probably a issue with Redis on https://github.com/crybapp/api, I'd open an issue there - will look into this tho!

**Comment by jeda** [comment]
Accidentally closing issue and sending comment before finished. Thanks phone.

**Comment by jeda** [comment]
Well, there's no errors at all anywhere by my observations last night, and I'm not sure of the real cause or where it was caused. I did this here as someone on the Cryb Discord server saw WebSockets errors with this exact issue.

**Comment by jeda** [comment]
Forgot to mention. They aren't synced until you reload the page or leave and rejoin the room.

**Comment by darnfish** [comment]
This definitely seems like a Redis issue where the pub/sub isn't properly sending / receiving messages. I'll look into it!

**Comment by darnfish** [comment]
Also, make sure your Redis server is running locally and `NODE_ENV` in .env in `@cryb/api` is set to `development`.

**Comment by jeda** [comment]
Hasn't this been fixed for now with crybapp/api@40b14add96e721c9ca7276d8fb16564d9b21a530?

**Comment by Akrilla** [comment]
Fixed crybapp/api@40b14ad
