### ISSUE TITLE
Leave and accept when invited to a room and the user is already in a room

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#37]
It would be nice if we could just leave and accept the invite in the screen instead of having to go back to the home screen, leaving, and then accepting.

![image](https://user-images.githubusercontent.com/26326692/67130942-e80a6e00-f1d0-11e9-9ef5-9084ecb2357f.png)

**Comment by darnfish** [comment]
You can click the 'leave the room you're in' tooltip to leave the room on this page, closing this for now but I can make it more visible with an underline. Thanks for the suggestion tho!

**Comment by Simonx22** [comment]
@williamsthing ohh you're right - didn't see that. Sorry!

**Comment by darnfish** [comment]
No worries 😄
