### ISSUE TITLE
Only animate avatars when you hover over them

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#39]
Just like in Discord, otherwise it might get really distracting

**Comment by darnfish** [comment]
There was actually support for this on our internal repo before we went open source, we used VueFreezeframe to handle the pause/playing of GIFs on hover. Maybe a better implementation could be worked on, but this is a good feature request!

![image](https://user-images.githubusercontent.com/8293444/67133360-4ac92d00-f204-11e9-9bfd-0bb58cd4a0b0.png)

**Comment by darnfish** [comment]
Actually looks like MinkiNTN has worked on this functionality, will close this issue out when https://github.com/crybapp/web/pull/42 is merged!
