### ISSUE TITLE
User icons appear twice

### ISSUE THREAD

**Issue by darnfish** [crybapp/web#41]
In some cases the user icon for a user appears twice. Unknown if this occurs for just the client or everyone in the room, or if the clients icon can only be shown twice or anyones icon can appear twice.

![image](https://user-images.githubusercontent.com/8293444/67131561-130ab700-f1fd-11e9-90a4-7834443bb3fa.png)

**Comment by darnfish** [comment]
Console errors
![image](https://user-images.githubusercontent.com/8293444/67131655-67159b80-f1fd-11e9-8ec6-18a2345c4459.png)

Looks like there's no user id duplicates in `onlineUsers` - weird!
![image](https://user-images.githubusercontent.com/8293444/67131633-56652580-f1fd-11e9-935b-233ba5ba1efa.png)

Appears twice in the `members` getter though.
![image](https://user-images.githubusercontent.com/8293444/67131679-8280a680-f1fd-11e9-8975-7bf96446be99.png)

**Comment by jeda** [comment]
As a personal opinion, I think they should appear twice only if there's two clients on it - and should show up for everyone. That, or add information as of multiple connections that appears when, for example, hovering. Shouldn't happen when it's not the case, though.

**Comment by darnfish** [comment]
I'm not too sure about this, I think once we fix client-side issues we can then look into how to handle multiple clients on the same room. @JeDaYoshi

**Comment by darnfish** [comment]
Fixed in https://github.com/crybapp/web/commit/c3f07bef941e5b0c9d67363ea9874c923f62fc8d, closing for now. Reopen if there are any further issues relating to this!
