### ISSUE TITLE
Special Keys are mapped after US-Keyboard

### ISSUE THREAD

**Issue by Chickenbreadlp** [crybapp/web#47]
I'm from germany and have a german keyboard. However, the VM only get's the keycode and has to figure out the input itself and thus special characters that the US Keyboard doesn't have don't work (ÄÖÜ) and all the special characters like @%&/... are mapped to different keys.
Because of this, you also can't paste stuff into the VM. Which might be crucial for some to log in.

My idea would be to handle the input on the client and only send the parsed input (the actual letters or symbols) to the VM.

**Comment by jeda** [comment]
This got fixed with #107. Closing!
