### ISSUE TITLE
No spacing between chat box and chat log on Firefox

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#48]
### Firefox: 

![image](https://user-images.githubusercontent.com/26326692/67151197-3d598480-f290-11e9-9f7f-b2603fe3d72a.png)

### Chrome:
![image](https://user-images.githubusercontent.com/26326692/67151202-4f3b2780-f290-11e9-9523-7440717473fb.png)

**Comment by darnfish** [comment]
I'll look into this soon 😄

**Comment by darnfish** [comment]
Fixed in https://github.com/crybapp/web/commit/33734cf643486aad93b34070d03ec6ff8a19f0a3, closing this for now - thanks for the report!
