### ISSUE TITLE
If room is deleted, people that aren't on it don't get removed

### ISSUE THREAD

**Issue by jeda** [crybapp/web#5]
Basically, I joined with two accounts. In one of them, I went back to /home, with its controls.

With my main account, I deleted the room, and it was normal, but in the other account, which was in /home...

![not okay!](https://safe.install.sex/sndyFg.png)
this doesn't gets updated, even if you join (which will tell you it doesn't exists) and going back. also gets stuck leaving the room:
![F](https://safe.install.sex/4GF0TO.png)
![not catching it..](https://safe.install.sex/3eR6n2.png)

Refreshing fixes it, but is not the correct behaviour.

**Comment by darnfish** [comment]
The `/home` page does not connect to `@cryb/api` via WebSocket, as WS connections to API are established on the `/room` page only. We might look into having the entire app connected to the `@cryb/api` WS server, but this will take a lot of refactoring. I'm gonna close this out for now, thanks for the feedback tho!

**Comment by jeda** [comment]
I think that at least, when getting a HTTP Error 410, it should take that the room has been already deleted and then remove all of those references, instead of refreshing so you can make a new room. Same if you join the room and it doesn't exists - works as a workaround for now.

**Comment by darnfish** [comment]
That can definitely be worked on, I'll re-open this and work on integrating that functionality.

**Comment by darnfish** [comment]
Fixed in https://github.com/crybapp/web/commit/0ce5c203bf142d596a1a532f9a9a34dfa27b6f47, closing unless there are any other issues!
