### ISSUE TITLE
Video goes deepfry-alike randomly

### ISSUE THREAD

**Issue by jeda** [crybapp/web#54]
I feel this is a network or encoding issue, but not sure. Example:

![old screenshot](https://cdn.discordapp.com/attachments/633728823401250846/634648065634205696/unknown.png)

**Comment by plusreed** [comment]
Do we know if this is actually with the frontend by chance? (If it's been discussed internally I haven't been keeping up :S)

It could possibly be [@cryb/portal](https://github.com/crybapp/portal)'s fault but I wouldn't really know.

**Comment by jeda** [comment]
@plusreed We think it's a problem with JSMpeg encoding - it even fixes itself *after a refresh* by user reports, which adds more thoughts into that.

**Comment by jeda** [comment]
Seems to be fixed for now with some of changes done in the past. Tell me if it keeps happening!
