### ISSUE TITLE
Refreshing the tab sometimes breaks the video player

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#55]
If I refresh the tab with an active VM I sometimes get this issue:

![image](https://user-images.githubusercontent.com/26326692/67155898-635d4400-f2e5-11e9-9345-15c695c7b4e7.png)

And all I'm able to see is this:

![image](https://user-images.githubusercontent.com/26326692/67155904-72dc8d00-f2e5-11e9-8ad6-6e0c87d7dd32.png)

Even though the VM is up and running. The only solution is to go back to /home and return to the room from there.

**Comment by jeda** [comment]
This should not be happening now. Feel free to comment if it does. Closing!
