### ISSUE TITLE
Smaller player sizes does not take up full size

### ISSUE THREAD

**Issue by darnfish** [crybapp/web#57]
It'd be better if smaller player sizes, such as 640x480 took up the full height and/or width based on the browser size of the player area. See below for an example of what the player currently looks like now at 640x480 👇 

![image](https://user-images.githubusercontent.com/8293444/67165503-c8fd0f00-f37d-11e9-9c64-641c7b7f85a7.png)

**Comment by Chickenbreadlp** [comment]
If you give the player a CSS height of 100% it takes up the full height of the player area, but squeezes if the play-area is less wide than 16:9.
The same goes for a CSS width of 100%, just that it stretches, when the play-area width is wider than 16:9

**Comment by jeda** [comment]
This got fixed with Janus, buuut still needs fixing with JSMpeg's player.
