### ISSUE TITLE
Not properly removing the room from cache?

### ISSUE THREAD

**Issue by jeda** [crybapp/web#6]
Related to #5. I joined another (recently created) room then, but then, in the account with the issue:
![uh oh](https://safe.install.sex/8Poli1.png)
![where are you?](https://safe.install.sex/mUMUho.png)

even though in my main account it shows it is on the room.

**Comment by darnfish** [comment]
Does refreshing these pages help?

**Comment by jeda** [comment]
Yes, refreshing it shows that it's joined in the room and joins it correctly - but still, undesired behaviour.

**Comment by darnfish** [comment]
We'll see if we can add a site-wide WebSocket implementation soon, but it shouldn't be a big issue for end users running Cryb off've one tab. I get what you mean tho, closing this for now and I'll add it to my Feature Wishlist!
