### ISSUE TITLE
Index page is not centered if the video has been disabled

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#64]
This is what it looks like without a video:

![image](https://user-images.githubusercontent.com/26326692/67256576-d980b880-f455-11e9-8474-c2aa0e800e95.png)

And this is what it looks like with the video enabled:

![image](https://user-images.githubusercontent.com/26326692/67256571-cff75080-f455-11e9-8c20-82d15f175b2e.png)

**Comment by darnfish** [comment]
I think this was fixed in https://github.com/crybapp/web/commit/63f54ae7128f851a25bc49c2a2d0afb1a120ba99, let me know if you're still having this issue after this commit.

**Comment by Simonx22** [comment]
Nope, this sadly hasn't been fixed by https://github.com/crybapp/web/commit/63f54ae7128f851a25bc49c2a2d0afb1a120ba99 @williamsthing

**Comment by darnfish** [comment]
I'll look into it!

**Comment by plusreed** [comment]
We think this could be a good first issue for those wanting to contribute to Cryb. If you want to hop on this issue, go right ahead! :+1:
