### ISSUE TITLE
Invite Not Found page is linking to a nonexistent support page

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#71]
![image](https://user-images.githubusercontent.com/26326692/67503206-38605080-f655-11e9-9600-2a47f16cf6f2.png)

**Comment by plusreed** [comment]
Part of me thinks we left this here before we went open source so we could eventually finish it. I guess we missed it.

@williamsthing Should we just remove the link or actually make a support page?

**Comment by darnfish** [comment]
Just remove all links to contact support I think

**Comment by plusreed** [comment]
I think this could be a good first issue for people who want to contribute to the project. So let's see if someone wants to pick it up :+1:

**Comment by jeda** [comment]
Fixed in 517f9b858. Closing!
