### ISSUE TITLE
Not getting redirected when destroying a room

### ISSUE THREAD

**Issue by jeda** [crybapp/web#8]
All stuff gets removed, but you need to click the Cryb logo to go to `/home` when a room has been destroyed.

**Comment by darnfish** [comment]
This is an internally known issue, will try and fix soon!

**Comment by darnfish** [comment]
Trying to reproduce this now, do you know anything you specifically did when this happened? @JeDaYoshi

**Comment by jeda** [comment]
Honestly, it happened before at much of... all times, but yesterday I was using it and it was working.

**Comment by darnfish** [comment]
I've encountered this issue before, haven't been able to reproduce it locally tho recently. Will try again

**Comment by jeda** [comment]
This was fixed a long time ago. Closing!
