### ISSUE TITLE
this.apertureWs is sometimes undefined, leading to only a black screen

### ISSUE THREAD

**Issue by jeda** [crybapp/web#9]
Doesn't seems to happen everytime.

https://github.com/crybapp/web/blob/4f4979c280f37b17bc1b4fe7f659f0c6a5f3ffb7/components/player/viewer.vue#L61

Sometimes this.apertureWs is not getting defined, leading to just a black screen, and no error at all - just it trying indefinitely to connect to `https://cryb.app/undefined/?t=token` - as an example.

![](https://safe.install.sex/1bVjBH.png)

**Comment by darnfish** [comment]
Good find, just pushed https://github.com/crybapp/web/commit/19b1c129894c2ea55f512000b9b0a67ba3f10d1b which will only show `viewer.vue` if `apertureWs` and `apertureToken` is defined. Closing this for now, lmk if there are any more issues.
